export const VIDEO_LIST_API_URL = '/videos';
export const FETCH_VIDEO_INFO_API_URL = 'https://www.googleapis.com/youtube/v3/videos';
export const VIDEO_CREATE_API_URL = '/video';

export const YOUTUBE_VIDEO_KEY = 'AIzaSyA5YEw2RGvy1ayky2XDPqz-ky2ahd7ttA4';

export const ACTION_TYPES = {
    FETCH_VIDEOS_INIT: 'FETCH_VIDEOS_INIT',
    FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
    FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',

    SHARE_VIDEO_INIT: 'SHARE_VIDEO_INIT',
    SHARE_VIDEO_SUCCESS: 'SHARE_VIDEO_SUCCESS',
    SHARE_VIDEO_FAILURE: 'SHARE_VIDEO_FAILURE'
};