export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const UN_AUTH = 'UN_AUTH';

export const FETCH_PROFILE_INIT = 'FETCH_PROFILE_INIT';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const FETCH_VIDEOS_INIT = 'FETCH_VIDEOS_INIT';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const SHARE_VIDEO_SUCCESS = 'SHARE_VIDEO_SUCCESS';
export const SHARE_VIDEO_FAILURE = 'SHARE_VIDEO_FAILURE';
